services:
  app:
    build:
      context: ./app
    ports:
      - 8080:8080
      - 5678:5678
    command: sh -c 
      "
      pip install debugpy &&
      python -m debugpy --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8080
      "
    healthcheck:
      test: python scripts/healthcheck.py
      retries: 3
      timeout: 3s
      start_period: 3s
      start_interval: 1s
      interval: 15s
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /home/app